server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    charset utf-8;
    client_max_body_size 10M;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; object-src 'none'; base-uri 'self';" always;
    fastcgi_hide_header X-Powered-By;

    # snippet view
    location ~ ^/p/([a-zA-Z0-9]+)/raw$ {
        try_files $uri /raw.php?slug=$1;
    }

    location ~ ^/p/([a-zA-Z0-9]+)$ {
        try_files $uri /view.php?slug=$1;
    }

    location = /api/paste {
        try_files $uri /api.php;
    }

    location ~ ^/api/fork/([a-zA-Z0-9]+)$ {
        try_files $uri /fork.php?slug=$1;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_X_REAL_IP  $remote_addr;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
